export const usersData = [
  {
    id: 1,
    username: "nbrookfield0",
    password: "password123",
    email: "nbrookfield0@feedburner.com",
    profilePic: null,
  },
  {
    id: 2,
    username: "eayscough1",
    password: "password123",
    email: "eayscough1@pagesperso-orange.fr",
    profilePic: null,
  },
  {
    id: 3,
    username: "dmconie2",
    password: "password123",
    email: "dmconie2@netscape.com",
    profilePic: null,
  },
  {
    id: 4,
    username: "hdalyiel3",
    password: "password123",
    email: "hdalyiel3@fc2.com",
    profilePic: null,
  },
  {
    id: 5,
    username: "mnibley4",
    password: "password123",
    email: "mnibley4@marketwatch.com",
    profilePic: null,
  },
  {
    id: 6,
    username: "john_doe",
    password: "password123",
    email: "john_doe@example.com",
    profilePic: null,
  },
  {
    id: 7,
    username: "jane_smith",
    password: "password123",
    email: "jane_smith@example.com",
    profilePic: null,
  },
  {
    id: 8,
    username: "lucas_perez",
    password: "password123",
    email: "lucas_perez@example.com",
    profilePic: null,
  },
  {
    id: 9,
    username: "emily_williams",
    password: "password123",
    email: "emily_williams@example.com",
    profilePic: null,
  },
  {
    id: 10,
    username: "chris_lee",
    password: "password123",
    email: "chris_lee@example.com",
    profilePic: null,
  },
];
